package simpledb;

import java.util.*;

import org.omg.CORBA.TypeCodeHolder;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;
    private JoinPredicate _p;
    private OpIterator _child1;
    private OpIterator _child2;
    private Tuple t1 = null, t2 = null;

    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, OpIterator child1, OpIterator child2) {
        _p = p;
        _child1 = child1;
        _child2 = child2;
    }

    public JoinPredicate getJoinPredicate() {
        return _p;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        return _child1.getTupleDesc().getFieldName(_p.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        return _child2.getTupleDesc().getFieldName(_p.getField2());
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        return TupleDesc.merge(_child1.getTupleDesc(), _child2.getTupleDesc());
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        _child1.open();
        _child2.open();
        super.open();
    }

    public void close() {
        _child1.close();
        _child2.close();
        super.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        _child1.rewind();
        _child2.rewind();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        while (_child1.hasNext() || t1 != null) {
            if (t1 == null) {
                t1 = _child1.next();
            }
            while (_child2.hasNext()) {
                t2 = _child2.next();
                if (_p.filter(t1, t2)) {
                    int size = t1.getTupleDesc().numFields() + t2.getTupleDesc().numFields();
                    Type[] typeAr = new Type[size];
                    String[] fieldAr = new String[size];
                    int i = 0, j = 0;
                    for (; i < t1.getTupleDesc().numFields(); i++) {
                        typeAr[i] = t1.getTupleDesc().getFieldType(i);
                        fieldAr[i] = t1.getTupleDesc().getFieldName(i);
                    }
                    for (; j < t2.getTupleDesc().numFields(); i++, j++) {
                        typeAr[i] = t2.getTupleDesc().getFieldType(j);
                        fieldAr[i] = t2.getTupleDesc().getFieldName(j);
                    }
                    TupleDesc td = new TupleDesc(typeAr, fieldAr);
                    Tuple t = new Tuple(td);
                    for (i = 0; i < t1.getTupleDesc().numFields(); i++) {
                        t.setField(i, t1.getField(i));
                    }
                    for (j = 0; j < t2.getTupleDesc().numFields(); i++, j++) {
                        t.setField(i, t2.getField(j));
                    }
                    return t;
                }
            }
            t1 = null;
            _child2.rewind();
        }
        return null;
    }

    @Override
    public OpIterator[] getChildren() {
        return new OpIterator[]{_child1, _child2};
    }

    @Override
    public void setChildren(OpIterator[] children) {
        _child1 = children[0];
        _child2 = children[1];
    }

}
